---
abstract: 'Simple data in SysV shared memory segments.'
author:
  - 'Kevin Cody-Little <kcody@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-Shm-Simple
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Class::Attrib: 1.06
  DynaLoader: 0
  Fcntl: 0
  IPC::SysV: 0
  UNIVERSAL: 0
resources:
  repository: https://github.com/kcodyjr/ipcshm-simple
version: 1.10
